<?php

namespace App\Controllers\Api;

use App\Controllers\BaseController;
use App\Libraries\FirmaAPI;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class Pokemon extends BaseController
{
    protected FirmaAPI $firmapi;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger): void
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
        $this->firmapi = new FirmaAPI($response);
    }

    public function getPokemon(int $pokemonId): ResponseInterface
    {
        $pokemon_model = new \App\Models\Pokemon\Pokemon_model(null, null, true);
        $pokemon = $pokemon_model->getPokemon($pokemonId);

        if($pokemon->statsLoaded !== 1) {
            $pokemon_model->loadPokemonStats($this->response, $pokemonId);

        }

        return $this->firmapi->defaultResponseOk($pokemon);
    }

    public function getPokemons(): ResponseInterface
    {
        $limit = $this->firmapi->getGet("limit") ?? 20;
        $offset = $this->firmapi->getGet("offset") ?? 0;

        return $this->firmapi->defaultResponseOk();
    }
}